name: Build kubectl image
on:
  schedule:
    - cron: '13 0 * * *' # This will run the job daily at 00:13
  workflow_dispatch: 

env:
  REGISTRY: ghcr.io

defaults:
  run:
    shell: bash

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest k8s version
        id: latest_k8s_version
        run: echo "version=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Prepare repository name
        id: prepare-repository-name
        run: |
          repository=$REGISTRY/${{ github.repository }}
          echo "repository=${repository,,}" >> $GITHUB_OUTPUT

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          tags: ${{ steps.prepare-repository-name.outputs.repository }}:${{ steps.latest_k8s_version.outputs.version }}
          cache-from: |
            type=gha,scope=sha-${{ github.sha }}
            type=gha,scope=${{ github.ref_name }}
            type=gha,scope=${{ github.base_ref || 'main' }}
            type=gha,scope=main
          cache-to: |
            type=gha,scope=sha-${{ github.sha }},mode=max
            type=gha,scope=${{ github.ref_name }},mode=max
          build-args:
            "KUBECTL_VERSION=${{ steps.latest_k8s_version.outputs.version }}"
          push: true
          labels: ${{ steps.extract-metadata.outputs.labels }}
